package entities

const (
	SIMULATION_DURATION = 365

	START_MONEY     = 100
	START_CAT_FOOD  = 30
	START_FOOD      = 50
	START_DIRTINESS = 0
	START_SATIETY   = 30
	START_HEPPINESS = 100

	HAPPINESS_REDUCTION_CUZ_DIRTY = 10
	HAPPINESS_FROM_PETTING_A_CAT  = 5
	HAPPINESS_FROM_PLAYING_PC     = 20

	EVERY_DAY_DIRNESS_INCREASE           = 5
	SATIETY_REDUCTION                    = 10
	DIRTINESS_INCREASE_FROM_TEARING_WALL = 5

	COAT_COST = 650
)
